version: 2.1

orbs:
  astradot-ci: astradot/circleci-orb-internal-ci-util@1

jobs:
  publish:
    docker:
      - image: cimg/node:16.15
    steps:
      - checkout
      - run:
          name: npm publish
          command: |
            npm ci
            npm run compile
            echo "//registry.npmjs.org/:_authToken=$NPM_PUBLIC_AUTH_TOKEN" > ~/.npmrc
            npm publish --access public
      - astradot-ci/slack-notify:
          msg: NPM Publish
          buildOnTag: true

workflows:
  build:
    jobs:
      - publish:
          context:
            - global
            - prod-deploy
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
